---
name: "CI - Maven"
"on":
- "push"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "setup JDK 21"
      uses: "actions/setup-java@v4"
      with:
        java-version: "21"
        distribution: "temurin"
    - name: "maven clean package"
      run: "./mvnw --batch-mode clean package"
